version: "3.2"
services:
  aspnet-react-production:
    image: vtrifonovdocker/http-web-api-container:stub-v1.0
    networks:
      external-net:
    ports: 
      - 45899:8080
    volumes:
      - "../wiremockStubs:/home/wiremock"
    container_name: http-web-api-container
networks:
  external-net: